# This file was auto-generated by Fern from our API Definition.

import enum


class ConductorQuantumEnvironment(enum.Enum):
    DEFAULT = "http://localhost:8080/v0"
    PRODUCTION = "https://api.conductorquantum.com/v0"
