# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class Model(UniversalBaseModel):
    name: str
    description: str
    inputs: typing.Dict[str, typing.Optional[typing.Any]]
    outputs: typing.Dict[str, typing.Optional[typing.Any]]
    example_input_data: str
    example_output_data: str
    str_id: str
    id: int
    created_at: dt.datetime
    number_of_runs: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
