# This file was auto-generated by Fern from our API Definition.

import typing

ModelsEnum = typing.Union[
    typing.Literal[
        "coulomb-blockade-peak-detector",
        "coulomb-blockade-classifier",
        "pinch-off-classifier",
        "pinch-off-parameter-extractor",
        "turn-on-classifier",
        "turn-on-parameter-extractor",
    ],
    typing.Any,
]
