# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class VoteResponse(UniversalBaseModel):
    """
    Response for a vote operation.
    """

    model_result_id: str = pydantic.Field()
    """
    External UUID of the model result
    """

    vote: int = pydantic.Field()
    """
    The vote value: 1 or -1
    """

    feedback: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional text feedback
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
